using GaziHastane.Data;
using GaziHastane.Security;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication.Cookies;
using Serilog;

namespace GaziHastane
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information()
                .WriteTo.Console()
                .WriteTo.File("Logs/SistemLog-.txt", rollingInterval: RollingInterval.Day)
                .CreateLogger();

            try
            {
                // PostgreSQL 6.0+ sürümlerinde DateTime.Local hatasını önlemek için 
                AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

                var builder = WebApplication.CreateBuilder(args);

                builder.Host.UseSerilog();

            // PostgreSQL veritabanı servisi ekleniyor
            builder.Services.AddDbContext<GaziHastaneContext>(options =>
                options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

            builder.Services.AddControllersWithViews(options =>
            {
                options.Filters.Add<AdminPagePermissionFilter>();
                options.Filters.Add<AdminActionLogFilter>();
            });

            // ------------------------------------------------------------------
            // KİMLİK DOĞRULAMA VE ÇEREZ (COOKIE) AYARLARI
            // ------------------------------------------------------------------
            builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
                .AddCookie(options =>
                {
                    options.LoginPath = "/Admin/Auth/Login"; // Giriş yapılmamışsa yönlendirilecek sayfa
                    options.LogoutPath = "/Admin/Auth/Logout"; // Çıkış yapıldığında gidilecek sayfa
                    options.AccessDeniedPath = "/Admin/Auth/Login"; // Yetkisiz erişimde yönlendirilecek sayfa
                    options.Cookie.Name = "GaziMedAdminAuth"; // Tarayıcıda tutulacak çerez (cookie) adı
                    options.ExpireTimeSpan = TimeSpan.FromHours(8); // Oturum 8 saat açık kalsın
                });

                var app = builder.Build();

                app.UseSerilogRequestLogging();

                // Veritabanına başlangıç verilerini ekle (Seed Data)
                using (var scope = app.Services.CreateScope())
                {
                    var services = scope.ServiceProvider;
                    try
                    {
                        var context = services.GetRequiredService<GaziHastaneContext>();
                        context.Database.Migrate();

                        context.Database.ExecuteSqlRaw("""
                            ALTER TABLE "Etkinlikler"
                            ADD COLUMN IF NOT EXISTS "GorselUrl" character varying(255);
                            """);

                        context.Database.ExecuteSqlRaw("""
                            ALTER TABLE "Etkinlikler"
                            ADD COLUMN IF NOT EXISTS "ModalIcerik" text;
                            """);

                        context.Database.ExecuteSqlRaw("""
                            CREATE TABLE IF NOT EXISTS "KurumsalSekmeler" (
                                "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "Baslik" VARCHAR(100) NOT NULL,
                                "SekmeId" VARCHAR(100) NOT NULL,
                                "Icerik" TEXT,
                                "IconClass" VARCHAR(100),
                                "Sira" INTEGER NOT NULL DEFAULT 99,
                                "AktifMi" BOOLEAN NOT NULL DEFAULT TRUE,
                                "SayfaKey" VARCHAR(50) NOT NULL
                            );
                            """);

                        context.Database.ExecuteSqlRaw("""
                            ALTER TABLE "KurumsalIcerikler"
                            ADD COLUMN IF NOT EXISTS "IcerikTipi" VARCHAR(20) NOT NULL DEFAULT 'Form';
                            """);

                        context.Database.ExecuteSqlRaw("""
                            ALTER TABLE "KurumsalIcerikler"
                            ADD COLUMN IF NOT EXISTS "VideoUrl" VARCHAR(500);
                            """);

                        DbInitializer.Initialize(context);
                    }
                    catch (Exception ex)
                    {
                        Log.Fatal(ex, "Veritabanı oluşturulurken veya veri eklenirken hata oluştu.");
                    }
                }

                if (!app.Environment.IsDevelopment())
                {
                    app.UseExceptionHandler("/Home/Error");
                    app.UseHsts();
                }

                app.UseHttpsRedirection();
                app.UseStaticFiles();

                app.UseRouting();

                // DİKKAT: UseAuthentication HER ZAMAN UseAuthorization'dan ÖNCE GELMELİ!
                app.UseAuthentication();
                app.UseAuthorization();

                // 1. AREA ROTASI (Admin paneli için)
                app.MapControllerRoute(
                    name: "areas",
                    pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");

                // 2. DEFAULT ROTA (Ziyaretçi önyüzü için)
                app.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");

                app.Run();
            }
            catch (Exception ex) when (!string.Equals(ex.GetType().Name, "HostAbortedException", StringComparison.Ordinal))
            {
                Log.Fatal(ex, "Uygulama beklenmeyen bir şekilde çöktü.");
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }
    }
}