-- WARNING: This script DROPS existing tables "Doktorlar" and "Bolumler" and recreates them.
-- Make a backup before running: pg_dump -h HOST -U USER -d DBNAME -Fc -f backup.dump

BEGIN;

-- Drop dependent table first
DROP TABLE IF EXISTS "Doktorlar" CASCADE;
DROP TABLE IF EXISTS "Bolumler" CASCADE;

-- Create Bolumler
CREATE TABLE "Bolumler" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad character varying(150) NOT NULL,
    aciklama text,
    fotografurl character varying(255),
    kategori character varying(255),
    isactive boolean NOT NULL DEFAULT true
);

-- Create Doktorlar
CREATE TABLE "Doktorlar" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kullaniciid integer,
    bolumid integer,
    unvan character varying(50),
    ad character varying(100) NOT NULL,
    soyad character varying(100) NOT NULL,
    uzmanlikalani character varying(150),
    ozgecmis text,
    fotografurl character varying(255),
    isactive boolean NOT NULL DEFAULT true,
    CONSTRAINT fk_doktor_kullanici FOREIGN KEY (kullaniciid) REFERENCES "Users"(id) ON DELETE SET NULL,
    CONSTRAINT fk_doktor_bolum FOREIGN KEY (bolumid) REFERENCES "Bolumler"(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_Doktorlar_BolumId" ON "Doktorlar" (bolumid);
CREATE INDEX IF NOT EXISTS "IX_Doktorlar_KullaniciId" ON "Doktorlar" (kullaniciid);

COMMIT;

-- Usage with psql (example):
-- PGPASSWORD=yourpass psql -h yourhost -U youruser -d yourdb -f scripts/recreate_bolum_doktor.sql

-- Or run inside pgAdmin Query Tool after taking backup.
