using GaziHastane.Models;
using GaziHastane.Security;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace GaziHastane.Data
{
    public static class DbInitializer
    {
        public static void Initialize(GaziHastaneContext context)
        {
            // Veritaban�n�n olu�turuldu�undan emin ol (E�er migration yap�lmad�ysa bunu olu�turur)
            context.Database.EnsureCreated();

            // HastaRehberi i�in geriye d�n�k kolon g�venli�i
            context.Database.ExecuteSqlRaw("ALTER TABLE \"HastaRehberi\" ADD COLUMN IF NOT EXISTS \"AcilisTipi\" character varying(20) NOT NULL DEFAULT 'Modal';");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"HastaRehberi\" ADD COLUMN IF NOT EXISTS \"HedefUrl\" character varying(500) NULL;");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"HastaRehberi\" ADD COLUMN IF NOT EXISTS \"ModalIcerik\" text NULL;");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"Yetkililer\" ADD COLUMN IF NOT EXISTS \"AdminSayfaYetkileri\" character varying(2000) NULL;");
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""AdminMenuItems"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Section"" character varying(50) NOT NULL,
                    ""PermissionKey"" character varying(50) NULL,
                    ""Url"" character varying(255) NOT NULL,
                    ""Label"" character varying(150) NOT NULL,
                    ""IconClass"" character varying(100) NULL,
                    ""Controller"" character varying(50) NULL,
                    ""Action"" character varying(50) NULL,
                    ""ActiveIconClass"" character varying(250) NULL,
                    ""HoverIconClass"" character varying(250) NULL,
                    ""SortOrder"" integer NOT NULL DEFAULT 1,
                    ""IsSuperAdminOnly"" boolean NOT NULL DEFAULT false,
                    ""IsActive"" boolean NOT NULL DEFAULT true
                );
            ");
            context.Database.ExecuteSqlRaw(@"
                INSERT INTO ""AdminMenuItems"" (""Section"", ""PermissionKey"", ""Url"", ""Label"", ""IconClass"", ""Controller"", ""HoverIconClass"", ""SortOrder"", ""IsSuperAdminOnly"", ""IsActive"")
                SELECT 'System', 'doktorrandevuplani', '/Admin/DoktorRandevuPlan/Index', 'Doktor Planlama', 'fa-solid fa-calendar-plus', 'DoktorRandevuPlan', 'group-hover:text-cyan-400', 8, false, true
                WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'AdminMenuItems')
                  AND NOT EXISTS (SELECT 1 FROM ""AdminMenuItems"" WHERE ""Controller"" = 'DoktorRandevuPlan');
            ");
            context.Database.ExecuteSqlRaw(@"
                INSERT INTO ""AdminMenuItems"" (""Section"", ""PermissionKey"", ""Url"", ""Label"", ""IconClass"", ""Controller"", ""Action"", ""HoverIconClass"", ""SortOrder"", ""IsSuperAdminOnly"", ""IsActive"")
                SELECT 'System', NULL, '/Admin/TahlilSonuclari/Giris', 'Tahlil Sonu� Giri�i', 'fa-solid fa-vials', 'TahlilSonuclari', 'Giris', 'group-hover:text-cyan-400', 9, false, true
                WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'AdminMenuItems')
                  AND NOT EXISTS (SELECT 1 FROM ""AdminMenuItems"" WHERE ""Controller"" = 'TahlilSonuclari' AND COALESCE(""Action"", '') = 'Giris');
            ");
            context.Database.ExecuteSqlRaw(@"
                INSERT INTO ""AdminMenuItems"" (""Section"", ""PermissionKey"", ""Url"", ""Label"", ""IconClass"", ""Controller"", ""Action"", ""HoverIconClass"", ""SortOrder"", ""IsSuperAdminOnly"", ""IsActive"")
                SELECT 'System', NULL, '/Admin/TahlilSonuclari/Sorgula', 'Tahlil Sonu� Sorgu', 'fa-solid fa-magnifying-glass-chart', 'TahlilSonuclari', 'Sorgula', 'group-hover:text-blue-400', 10, false, true
                WHERE EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'AdminMenuItems')
                  AND NOT EXISTS (SELECT 1 FROM ""AdminMenuItems"" WHERE ""Controller"" = 'TahlilSonuclari' AND COALESCE(""Action"", '') = 'Sorgula');
            ");
            context.Database.ExecuteSqlRaw(@"
                UPDATE ""AdminMenuItems""
                SET ""Section"" = 'System', ""SortOrder"" = 8
                WHERE ""Controller"" = 'DoktorRandevuPlan';
            ");
            context.Database.ExecuteSqlRaw(@"
                UPDATE ""AdminMenuItems""
                SET ""Section"" = 'System', ""SortOrder"" = 9
                WHERE ""Controller"" = 'TahlilSonuclari' AND COALESCE(""Action"", '') = 'Giris';
            ");
            context.Database.ExecuteSqlRaw(@"
                UPDATE ""AdminMenuItems""
                SET ""Section"" = 'System', ""SortOrder"" = 10
                WHERE ""Controller"" = 'TahlilSonuclari' AND COALESCE(""Action"", '') = 'Sorgula';
            ");
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""PanelAyarlar"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""AyarKey"" character varying(100) NOT NULL,
                    ""AyarValue"" character varying(500) NOT NULL
                );
            ");
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""Belgeler"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Baslik"" character varying(255) NOT NULL,
                    ""DosyaYolu"" character varying(500) NOT NULL,
                    ""DosyaTipi"" character varying(50) NULL,
                    ""YuklenmeTarihi"" timestamp without time zone NOT NULL,
                    ""IsActive"" boolean NOT NULL DEFAULT true
                );
            ");
            context.Database.ExecuteSqlRaw(@"
                INSERT INTO ""PanelAyarlar"" (""AyarKey"", ""AyarValue"")
                SELECT 'DoktorGunlukRandevuKapasitesi', '24'
                WHERE NOT EXISTS (
                    SELECT 1 FROM ""PanelAyarlar"" WHERE ""AyarKey"" = 'DoktorGunlukRandevuKapasitesi'
                );
            ");
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""DoktorRandevuPlanlari"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""DoktorId"" integer NOT NULL,
                    ""BolumId"" integer NULL,
                    ""Yil"" integer NOT NULL,
                    ""Ay"" integer NOT NULL,
                    ""SlotSureDakika"" integer NOT NULL DEFAULT 30,
                    ""BaslangicSaati"" interval NOT NULL DEFAULT interval '09:00:00',
                    ""BitisSaati"" interval NOT NULL DEFAULT interval '17:00:00',
                    ""OgleMolaBaslangicSaati"" interval NOT NULL DEFAULT interval '12:00:00',
                    ""OgleMolaBitisSaati"" interval NOT NULL DEFAULT interval '13:00:00'
                );
            ");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"DoktorRandevuPlanlari\" ADD COLUMN IF NOT EXISTS \"OgleMolaBaslangicSaati\" interval NOT NULL DEFAULT interval '12:00:00';");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"DoktorRandevuPlanlari\" ADD COLUMN IF NOT EXISTS \"OgleMolaBitisSaati\" interval NOT NULL DEFAULT interval '13:00:00';");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"DoktorRandevuPlanlari\" DROP COLUMN IF EXISTS \"AylikMaxRandevu\";");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"DoktorRandevuPlanlari\" DROP COLUMN IF EXISTS \"MolaHerHastaSayisi\";");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"DoktorRandevuPlanlari\" DROP COLUMN IF EXISTS \"MolaSureDakika\";");
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""DoktorRandevuPlanGunleri"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""PlanId"" integer NOT NULL,
                    ""Tarih"" timestamp without time zone NOT NULL,
                    ""IsRandevuAcik"" boolean NOT NULL DEFAULT true,
                    ""GunlukRandevuSayisi"" integer NOT NULL DEFAULT 20,
                    ""BaslangicSaati"" interval NULL,
                    ""BitisSaati"" interval NULL
                );
            ");
            try { context.Database.ExecuteSqlRaw("ALTER TABLE \"DoktorRandevuPlanGunleri\" RENAME COLUMN \"GunlukMaxRandevu\" TO \"GunlukRandevuSayisi\";"); } catch { }
            context.Database.ExecuteSqlRaw("ALTER TABLE \"DoktorRandevuPlanGunleri\" ADD COLUMN IF NOT EXISTS \"GunlukRandevuSayisi\" integer NOT NULL DEFAULT 20;");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"DoktorRandevuPlanGunleri\" DROP COLUMN IF EXISTS \"MolaHerHastaSayisi\";");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"DoktorRandevuPlanGunleri\" DROP COLUMN IF EXISTS \"MolaSureDakika\";");

            // 1. YEMEK L�STES� KONTROL� VE EKLEME
            if (!context.YemekListesi.Any())
            {
                var bugun = DateTime.Today;

                var yemekler = new YemekListesi[]
                {
                    // Bug�n�n Yemekleri
                    new YemekListesi { Tarih = bugun, Ogun = 1, Corba = "�ay", AnaYemek = "Ha�lanm�� Yumurta", YardimciYemek = "Beyaz Peynir", TatliMeyve = "Siyah Zeytin", ToplamKalori = 450 },
                    new YemekListesi { Tarih = bugun, Ogun = 2, Corba = "Mercimek �orbas�", AnaYemek = "�zmir K�fte", YardimciYemek = "Pirin� Pilav�", TatliMeyve = "Kemalpa�a Tatl�s�", ToplamKalori = 850 },
                    new YemekListesi { Tarih = bugun, Ogun = 3, Corba = "Ezogelin �orbas�", AnaYemek = "Taze Fasulye", YardimciYemek = "Bulgur Pilav�", TatliMeyve = "Mevsim Meyvesi", ToplamKalori = 700 },

                    // Yar�n�n Yemekleri
                    new YemekListesi { Tarih = bugun.AddDays(1), Ogun = 1, Corba = "S�t", AnaYemek = "Omlet", YardimciYemek = "Ka�ar Peyniri", TatliMeyve = "Bal-Tereya�", ToplamKalori = 500 },
                    new YemekListesi { Tarih = bugun.AddDays(1), Ogun = 2, Corba = "Tarhana �orbas�", AnaYemek = "Pili� Topkap�", YardimciYemek = "Meyhane Pilav�", TatliMeyve = "S�tla�", ToplamKalori = 800 },
                    new YemekListesi { Tarih = bugun.AddDays(1), Ogun = 3, Corba = "Yayla �orbas�", AnaYemek = "Karn�yar�k", YardimciYemek = "Cac�k", TatliMeyve = "Elma", ToplamKalori = 750 },
                };

                // Verileri veritaban� kontekstine ekle
                context.YemekListesi.AddRange(yemekler);
                context.SaveChanges();
                if (!context.KurumsalSekmeler.Any())
                {
                    context.KurumsalSekmeler.AddRange(
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Genel Bilgi", SekmeId = "genel-bilgi", Icerik = "<h3>Hastane Hakk�nda</h3><p>Gazi Hastanesi, b�lgenin en k�kl� sa�l�k kurulu�lar�ndan biridir...</p>", Sira = 1, IconClass = "fa-solid fa-hospital" },
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Misyon & Vizyon", SekmeId = "misyon-vizyon", Icerik = "<h3>Misyonumuz</h3><p>Kaliteli sa�l�k hizmeti sunmak...</p>", Sira = 2, IconClass = "fa-solid fa-eye" }
                    );
                    context.SaveChanges();
                }
            }

            // 2. B�L�M VE DOKTOR KONTROL� VE EKLEME
            if (!context.Bolumler.Any())
            {
                // �NEML�: Aray�zde g�r�nmesi i�in 'Kategori' alanlar� (Dahili, Cerrahi, Temel) eklendi!
                var bolumler = new Bolum[] {
                     new Bolum { Ad = "Kardiyoloji", Aciklama = "Kalp sa�l��� birimi", Kategori = "Dahili", IsActive = true },
                     new Bolum { Ad = "Genel Cerrahi", Aciklama = "Cerrahi m�dahaleler", Kategori = "Cerrahi", IsActive = true },
                     new Bolum { Ad = "Anatomi", Aciklama = "�nsan anatomisi", Kategori = "Temel", IsActive = true },
                     new Bolum { Ad = "G�z Hastal�klar�", Aciklama = "G�z ve g�rme sa�l���", Kategori = "Dahili", IsActive = true },
                     new Bolum { Ad = "Acil T�p", Aciklama = "7/24 Acil Servis", Kategori = "Dahili", IsActive = true }
                 };
                context.Bolumler.AddRange(bolumler);

                // B�l�mleri �nce kaydet ki ID'leri olu�sun (Doktor eklerken laz�m olacak)
                context.SaveChanges();
                if (!context.KurumsalSekmeler.Any())
                {
                    context.KurumsalSekmeler.AddRange(
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Genel Bilgi", SekmeId = "genel-bilgi", Icerik = "<h3>Hastane Hakk�nda</h3><p>Gazi Hastanesi, b�lgenin en k�kl� sa�l�k kurulu�lar�ndan biridir...</p>", Sira = 1, IconClass = "fa-solid fa-hospital" },
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Misyon & Vizyon", SekmeId = "misyon-vizyon", Icerik = "<h3>Misyonumuz</h3><p>Kaliteli sa�l�k hizmeti sunmak...</p>", Sira = 2, IconClass = "fa-solid fa-eye" }
                    );
                    context.SaveChanges();
                }

                // �rnek Doktor Ekle
                var kardiyoloji = context.Bolumler.FirstOrDefault(b => b.Ad == "Kardiyoloji");
                if (kardiyoloji != null)
                {
                    context.Doktorlar.Add(new Doktor
                    {
                        Ad = "Hasret",
                        Soyad = "�zdemir",
                        Unvan = "Uzman Dr.",
                        BolumId = kardiyoloji.Id,
                        UzmanlikAlani = "Kalp Yetmezli�i",
                        IsActive = true
                    });
                }

                context.SaveChanges();
                if (!context.KurumsalSekmeler.Any())
                {
                    context.KurumsalSekmeler.AddRange(
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Genel Bilgi", SekmeId = "genel-bilgi", Icerik = "<h3>Hastane Hakk�nda</h3><p>Gazi Hastanesi, b�lgenin en k�kl� sa�l�k kurulu�lar�ndan biridir...</p>", Sira = 1, IconClass = "fa-solid fa-hospital" },
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Misyon & Vizyon", SekmeId = "misyon-vizyon", Icerik = "<h3>Misyonumuz</h3><p>Kaliteli sa�l�k hizmeti sunmak...</p>", Sira = 2, IconClass = "fa-solid fa-eye" }
                    );
                    context.SaveChanges();
                }
            }

            // 3. YETK�L�LER (ADMIN) - E�er yoksa bir y�netici ekle
            if (!context.Yetkililer.Any())
            {
                // D�KKAT: SifreHash �u an d�z metin olarak kullan�l�yor. �retimde hash uygulay�n.
                var admin = new Yetkili
                {
                    AdSoyad = "Admin Kullan�c�",
                    Email = "admin@gazihastanesi.com",
                    SifreHash = "admin123",
                    Rol = "S�per Admin",
                    AdminSayfaYetkileri = AdminPanelPermissions.Serialize(AdminPanelPermissions.AllKeys),
                    IsActive = true,
                    KayitTarihi = DateTime.UtcNow
                };
                context.Yetkililer.Add(admin);
                context.SaveChanges();
                if (!context.KurumsalSekmeler.Any())
                {
                    context.KurumsalSekmeler.AddRange(
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Genel Bilgi", SekmeId = "genel-bilgi", Icerik = "<h3>Hastane Hakk�nda</h3><p>Gazi Hastanesi, b�lgenin en k�kl� sa�l�k kurulu�lar�ndan biridir...</p>", Sira = 1, IconClass = "fa-solid fa-hospital" },
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Misyon & Vizyon", SekmeId = "misyon-vizyon", Icerik = "<h3>Misyonumuz</h3><p>Kaliteli sa�l�k hizmeti sunmak...</p>", Sira = 2, IconClass = "fa-solid fa-eye" }
                    );
                    context.SaveChanges();
                }
            }
            else
            {
                var tumYetkiler = AdminPanelPermissions.Serialize(AdminPanelPermissions.AllKeys);

                var eksikSayfaIzniOlanlar = context.Yetkililer
                    .Where(x => string.IsNullOrWhiteSpace(x.AdminSayfaYetkileri))
                    .ToList();

                foreach (var yetkili in eksikSayfaIzniOlanlar)
                {
                    yetkili.AdminSayfaYetkileri = tumYetkiler;
                }

                if (!context.Yetkililer.Any(x => x.Rol == "S�per Admin"))
                {
                    var ilkYetkili = context.Yetkililer.OrderBy(x => x.Id).FirstOrDefault();
                    if (ilkYetkili != null)
                    {
                        ilkYetkili.Rol = "S�per Admin";
                        ilkYetkili.AdminSayfaYetkileri = tumYetkiler;
                    }
                }

                context.SaveChanges();
                if (!context.KurumsalSekmeler.Any())
                {
                    context.KurumsalSekmeler.AddRange(
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Genel Bilgi", SekmeId = "genel-bilgi", Icerik = "<h3>Hastane Hakk�nda</h3><p>Gazi Hastanesi, b�lgenin en k�kl� sa�l�k kurulu�lar�ndan biridir...</p>", Sira = 1, IconClass = "fa-solid fa-hospital" },
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Misyon & Vizyon", SekmeId = "misyon-vizyon", Icerik = "<h3>Misyonumuz</h3><p>Kaliteli sa�l�k hizmeti sunmak...</p>", Sira = 2, IconClass = "fa-solid fa-eye" }
                    );
                    context.SaveChanges();
                }
            }

            // 4. KURUMSAL SIDEBAR MEN� TOHUMLAMA
            if (!context.KurumsalMenuGruplar.Any())
            {
                var grupYonetim = new KurumsalMenuGrup
                {
                    GrupAdi = "Y�netim",
                    Sira = 1,
                    AktifMi = true
                };

                var grupKurumsal = new KurumsalMenuGrup
                {
                    GrupAdi = "Kurumsal",
                    Sira = 2,
                    AktifMi = true
                };

                context.KurumsalMenuGruplar.AddRange(grupYonetim, grupKurumsal);
                context.SaveChanges();
                if (!context.KurumsalSekmeler.Any())
                {
                    context.KurumsalSekmeler.AddRange(
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Genel Bilgi", SekmeId = "genel-bilgi", Icerik = "<h3>Hastane Hakk�nda</h3><p>Gazi Hastanesi, b�lgenin en k�kl� sa�l�k kurulu�lar�ndan biridir...</p>", Sira = 1, IconClass = "fa-solid fa-hospital" },
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Misyon & Vizyon", SekmeId = "misyon-vizyon", Icerik = "<h3>Misyonumuz</h3><p>Kaliteli sa�l�k hizmeti sunmak...</p>", Sira = 2, IconClass = "fa-solid fa-eye" }
                    );
                    context.SaveChanges();
                }

                var menuler = new KurumsalMenu[]
                {
                    new KurumsalMenu { GrupId = grupYonetim.Id, Baslik = "Ba�hekimlik", Url = "/Kurumsal/Bashekimlik", IconClass = "fa-user-tie", Sira = 1, AktifMi = true },
                    new KurumsalMenu { GrupId = grupYonetim.Id, Baslik = "Ba�m�d�rl�k", Url = "/Kurumsal/Basmudurluk", IconClass = "fa-users", Sira = 2, AktifMi = true },

                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "Hakk�m�zda", Url = "/Kurumsal/Index", IconClass = "fa-circle-info", Sira = 1, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "Hem�irelik Hizmetleri", Url = "/Kurumsal/HemsirelikHizmetleri", IconClass = "fa-user-nurse", Sira = 2, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "Bilgi ��lem Merkezi", Url = "/Kurumsal/BilgiIslem", IconClass = "fa-microchip", Sira = 3, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "�� Sa�l��� ve G�venli�i", Url = "/Kurumsal/IsSagligi", IconClass = "fa-shield-halved", Sira = 4, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "Enfeksiyon Kontrol", Url = "/Kurumsal/Enfeksiyon", IconClass = "fa-virus-slash", Sira = 5, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "Eczac�l�k Hizmetleri", Url = "/Kurumsal/Eczacilik", IconClass = "fa-pills", Sira = 6, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "Sat�n Alma", Url = "/Kurumsal/SatinAlma", IconClass = "fa-cart-shopping", Sira = 7, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "�statistik ve Raporlama", Url = "/Kurumsal/Istatistik", IconClass = "fa-chart-line", Sira = 8, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "Ar�iv Birimi", Url = "/Kurumsal/Arsiv", IconClass = "fa-box-archive", Sira = 9, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "Hasta �leti�im Birimi", Url = "/Kurumsal/HastaIletisim", IconClass = "fa-comment-medical", Sira = 10, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "�� Ak�� �emalar�", Url = "/Kurumsal/IsAkis", IconClass = "fa-diagram-project", Sira = 11, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "Organizasyon �emalar�", Url = "/Kurumsal/Organizasyon", IconClass = "fa-sitemap", Sira = 12, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "�� Kontrol", Url = "/Kurumsal/IcKontrol", IconClass = "fa-check-double", Sira = 13, AktifMi = true },
                    new KurumsalMenu { GrupId = grupKurumsal.Id, Baslik = "Bas�n ve Kurumsal �leti�im", Url = "/Kurumsal/BasinIletisim", IconClass = "fa-bullhorn", Sira = 14, AktifMi = true }
                };

                context.KurumsalMenuler.AddRange(menuler);
                context.SaveChanges();
                if (!context.KurumsalSekmeler.Any())
                {
                    context.KurumsalSekmeler.AddRange(
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Genel Bilgi", SekmeId = "genel-bilgi", Icerik = "<h3>Hastane Hakk�nda</h3><p>Gazi Hastanesi, b�lgenin en k�kl� sa�l�k kurulu�lar�ndan biridir...</p>", Sira = 1, IconClass = "fa-solid fa-hospital" },
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Misyon & Vizyon", SekmeId = "misyon-vizyon", Icerik = "<h3>Misyonumuz</h3><p>Kaliteli sa�l�k hizmeti sunmak...</p>", Sira = 2, IconClass = "fa-solid fa-eye" }
                    );
                    context.SaveChanges();
                }
            }

            // 5. ADMIN SIDEBAR MEN� TOHUMLAMA
            if (!context.AdminMenuItems.Any())
            {
                var menuItems = new AdminMenuItem[]
                {
                    new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.Dashboard, Url = "/Admin/Home/Index", Label = "G�sterge Paneli", IconClass = "fa-solid fa-cube", Controller = "Home", HoverIconClass = "group-hover:text-cyan-400", SortOrder = 1 },
                    new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.Doktorlar, Url = "/Admin/Doktorlar/Index", Label = "Doktorlar", IconClass = "fa-solid fa-user-doctor", Controller = "Doktorlar", HoverIconClass = "group-hover:text-purple-400", SortOrder = 2 },
                    new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.Bolumler, Url = "/Admin/Bolumler/Index", Label = "Poliklinikler", IconClass = "fa-solid fa-network-wired", Controller = "Bolumler", HoverIconClass = "group-hover:text-pink-400", SortOrder = 3 },
                    new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.HastaRehberi, Url = "/Admin/HastaRehberi/Index", Label = "Hasta Rehberi", IconClass = "fa-solid fa-book-medical", Controller = "HastaRehberi", HoverIconClass = "group-hover:text-emerald-400", SortOrder = 4 },
                    new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.Iletisim, Url = "/Admin/Iletisim/Index", Label = "�leti�im", IconClass = "fa-solid fa-address-book", Controller = "Iletisim", HoverIconClass = "group-hover:text-orange-400", SortOrder = 5 },

                    new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.KaliteYonetimi, Url = "/Admin/HizliIslem/Kalite", Label = "Kalite Y�netimi", IconClass = "fa-solid fa-shield-heart", Controller = "HizliIslem", Action = "Kalite", HoverIconClass = "group-hover:text-blue-400", SortOrder = 1 },
                    new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.Egitim, Url = "/Admin/Egitim/Index", Label = "E�itim Komitesi", IconClass = "fa-solid fa-graduation-cap", Controller = "Egitim", HoverIconClass = "group-hover:text-orange-500", SortOrder = 2 },
                    new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.YemekListesi, Url = "/Admin/HizliIslem/YemekListesi", Label = "Yemek Listesi", IconClass = "fa-solid fa-utensils", Controller = "HizliIslem", Action = "YemekListesi", HoverIconClass = "group-hover:text-orange-500", SortOrder = 3 },
                    new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.Kroki, Url = "/Admin/Kroki/Index", Label = "Kroki Y�netimi", IconClass = "fa-solid fa-map-location-dot", Controller = "Kroki", HoverIconClass = "group-hover:text-cyan-400", SortOrder = 4 },
                    new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.Medya, Url = "/Admin/HizliIslem/Gorsel", Label = "G�rseller", IconClass = "fa-solid fa-images", Controller = "HizliIslem", Action = "Gorsel", ActiveIconClass = "text-pink-500 drop-shadow-[0_0_8px_rgba(236,72,153,0.8)] scale-110", HoverIconClass = "group-hover:text-pink-400 group-hover:scale-110", SortOrder = 5 },
                    new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.Medya, Url = "/Admin/HizliIslem/AnaSayfaGorsel", Label = "Ana Sayfa Slider", IconClass = "fa-solid fa-image", Controller = "HizliIslem", Action = "AnaSayfaGorsel", ActiveIconClass = "text-yellow-500 drop-shadow-[0_0_8px_rgba(234,179,8,0.8)] scale-110", HoverIconClass = "group-hover:text-yellow-400 group-hover:scale-110", SortOrder = 6 },
                    new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.Medya, Url = "/Admin/HizliIslem/Belge", Label = "Belgeler", IconClass = "fa-solid fa-file-lines", Controller = "HizliIslem", Action = "Belge", ActiveIconClass = "text-blue-500 drop-shadow-[0_0_8px_rgba(59,130,246,0.8)] scale-110", HoverIconClass = "group-hover:text-blue-400 group-hover:scale-110", SortOrder = 7 },
                    new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.DoktorRandevuPlani, Url = "/Admin/DoktorRandevuPlan/Index", Label = "Doktor Planlama", IconClass = "fa-solid fa-calendar-plus", Controller = "DoktorRandevuPlan", HoverIconClass = "group-hover:text-cyan-400", SortOrder = 8 },

                    new() { Section = "Content", PermissionKey = AdminPanelPermissions.Keys.DijitalIslemler, Url = "/Admin/HizliIslem/Index", Label = "Dijital ��lemler", IconClass = "fa-solid fa-layer-group", Controller = "HizliIslem", Action = "Index", ActiveIconClass = "neon-icon text-cyan-400", HoverIconClass = "group-hover:text-cyan-400", SortOrder = 1 },
                    new() { Section = "Content", PermissionKey = AdminPanelPermissions.Keys.Haberler, Url = "/Admin/Haberler/Index", Label = "Haberler", IconClass = "fa-solid fa-newspaper", Controller = "Haberler", HoverIconClass = "group-hover:text-blue-400", SortOrder = 2 },
                    new() { Section = "Content", PermissionKey = AdminPanelPermissions.Keys.Etkinlikler, Url = "/Admin/Etkinlikler/Index", Label = "Etkinlikler", IconClass = "fa-solid fa-calendar-days", Controller = "Etkinlikler", HoverIconClass = "group-hover:text-fuchsia-400", SortOrder = 3 },
                    new() { Section = "Content", PermissionKey = AdminPanelPermissions.Keys.Duyurular, Url = "/Admin/Duyurular/Index", Label = "Duyurular", IconClass = "fa-solid fa-bullhorn", Controller = "Duyurular", HoverIconClass = "group-hover:text-yellow-400", SortOrder = 4 },

                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/Index", Label = "Sidebar Y�netimi", Controller = "Kurumsal", Action = "Index", SortOrder = 1 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Bashekimlik/Index", Label = "Ba�hekimlik", Controller = "Bashekimlik", Action = "Index", SortOrder = 2 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Basmudurluk/Index", Label = "Ba�m�d�rl�k", Controller = "Basmudurluk", Action = "Index", SortOrder = 3 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/HemsirelikHizmetleri", Label = "Hem�irelik Hizmetleri", Controller = "Kurumsal", Action = "HemsirelikHizmetleri", SortOrder = 4 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/BilgiIslemMerkezi", Label = "Bilgi ��lem Merkezi", Controller = "Kurumsal", Action = "BilgiIslemMerkezi", SortOrder = 5 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/IsSagligiVeGuvenligi", Label = "�� Sa�l��� ve G�venli�i", Controller = "Kurumsal", Action = "IsSagligiVeGuvenligi", SortOrder = 6 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/EnfeksiyonKontrol", Label = "Enfeksiyon Kontrol", Controller = "Kurumsal", Action = "EnfeksiyonKontrol", SortOrder = 7 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/EczacilikHizmetleri", Label = "Eczac�l�k Hizmetleri", Controller = "Kurumsal", Action = "EczacilikHizmetleri", SortOrder = 8 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/SatinAlma", Label = "Sat�n Alma", Controller = "Kurumsal", Action = "SatinAlma", SortOrder = 9 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/IstatistikVeRaporlama", Label = "�statistik ve Raporlama", Controller = "Kurumsal", Action = "IstatistikVeRaporlama", SortOrder = 10 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/ArsivBirimi", Label = "Ar�iv Birimi", Controller = "Kurumsal", Action = "ArsivBirimi", SortOrder = 11 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/HastaIletisimBirimi", Label = "Hasta �leti�im Birimi", Controller = "Kurumsal", Action = "HastaIletisimBirimi", SortOrder = 12 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/IsAkisSemalari", Label = "�� Ak�� �emalar�", Controller = "Kurumsal", Action = "IsAkisSemalari", SortOrder = 13 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/OrganizasyonSemalari", Label = "Organizasyon �emalar�", Controller = "Kurumsal", Action = "OrganizasyonSemalari", SortOrder = 14 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/IcKontrol", Label = "�� Kontrol", Controller = "Kurumsal", Action = "IcKontrol", SortOrder = 15 },
                    new() { Section = "KurumsalSub", PermissionKey = AdminPanelPermissions.Keys.Kurumsal, Url = "/Admin/Kurumsal/BasinVeKurumsalIletisim", Label = "Bas�n ve Kurumsal �leti�im", Controller = "Kurumsal", Action = "BasinVeKurumsalIletisim", SortOrder = 16 },

                    new() { Section = "Security", Url = "/Admin/Yetkililer/Index", Label = "Yetkili Listesi", IconClass = "fa-solid fa-user-shield", Controller = "Yetkililer", Action = "Index", HoverIconClass = "group-hover:text-rose-400", IsSuperAdminOnly = true, SortOrder = 1 }
                };

                context.AdminMenuItems.AddRange(menuItems);
                context.SaveChanges();
                if (!context.KurumsalSekmeler.Any())
                {
                    context.KurumsalSekmeler.AddRange(
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Genel Bilgi", SekmeId = "genel-bilgi", Icerik = "<h3>Hastane Hakk�nda</h3><p>Gazi Hastanesi, b�lgenin en k�kl� sa�l�k kurulu�lar�ndan biridir...</p>", Sira = 1, IconClass = "fa-solid fa-hospital" },
                        new KurumsalSekme { SayfaKey = "hakkimizda", Baslik = "Misyon & Vizyon", SekmeId = "misyon-vizyon", Icerik = "<h3>Misyonumuz</h3><p>Kaliteli sa�l�k hizmeti sunmak...</p>", Sira = 2, IconClass = "fa-solid fa-eye" }
                    );
                    context.SaveChanges();
                }
            }
        }
    }
}