using GaziHastane.Models;
using GaziHastane.Security;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace GaziHastane.Data
{
    public static class DbInitializer
    {
        public static void Initialize(GaziHastaneContext context)
        {
            // PostgreSQL Legacy Timestamp Behavior
            AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

            // Veritabanı oluşturulduğundan emin ol
            context.Database.EnsureCreated();

            // Karakter bozulmalarını temizlemek için AdminMenuItems tablosunu sıfırlayalım ve yeniden tohumlayalım (isteğe bağlı ama kesin çözüm)
            // context.Database.ExecuteSqlRaw("DELETE FROM \"AdminMenuItems\""); 

            // Tablo yapılarını güncelle (Migration alternatifi)
            context.Database.ExecuteSqlRaw("ALTER TABLE \"HastaRehberi\" ADD COLUMN IF NOT EXISTS \"AcilisTipi\" character varying(20) NOT NULL DEFAULT 'Modal';");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"HastaRehberi\" ADD COLUMN IF NOT EXISTS \"HedefUrl\" character varying(500) NULL;");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"HastaRehberi\" ADD COLUMN IF NOT EXISTS \"ModalIcerik\" text NULL;");
            context.Database.ExecuteSqlRaw("ALTER TABLE \"Yetkililer\" ADD COLUMN IF NOT EXISTS \"AdminSayfaYetkileri\" character varying(2000) NULL;");
            
            context.Database.ExecuteSqlRaw(@"
                CREATE TABLE IF NOT EXISTS ""AdminMenuItems"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Section"" character varying(50) NOT NULL,
                    ""PermissionKey"" character varying(50) NULL,
                    ""Url"" character varying(255) NOT NULL,
                    ""Label"" character varying(150) NOT NULL,
                    ""IconClass"" character varying(100) NULL,
                    ""Controller"" character varying(50) NULL,
                    ""Action"" character varying(50) NULL,
                    ""ActiveIconClass"" character varying(250) NULL,
                    ""HoverIconClass"" character varying(250) NULL,
                    ""SortOrder"" integer NOT NULL DEFAULT 1,
                    ""IsSuperAdminOnly"" boolean NOT NULL DEFAULT false,
                    ""IsActive"" boolean NOT NULL DEFAULT true
                );
            ");

            // Karakter bozukluğu olan kayıtları temizleyelim (Filtreleme ile)
            context.Database.ExecuteSqlRaw("DELETE FROM \"AdminMenuItems\" WHERE \"Label\" LIKE '%ï¿½%' OR \"Label\" LIKE '%Ã%'");
            context.Database.ExecuteSqlRaw("DELETE FROM \"AdminMenuItems\" WHERE \"Url\" LIKE '%BorcYonetim%'");

            // Eksik menüleri ekle
            SeedAdminMenus(context);

            // Diğer tabloları kontrol et
            if (!context.PanelAyarlari.Any())
            {
                context.PanelAyarlari.Add(new PanelAyar { AyarKey = "DoktorGunlukRandevuKapasitesi", AyarValue = "24" });
                context.SaveChanges();
            }

            // Yemek Listesi
            if (!context.YemekListesi.Any())
            {
                var bugun = DateTime.Today;
                context.YemekListesi.AddRange(
                    new YemekListesi { Tarih = bugun, Ogun = 1, Corba = "Çay", AnaYemek = "Haşlanmış Yumurta", YardimciYemek = "Beyaz Peynir", TatliMeyve = "Siyah Zeytin", ToplamKalori = 450 },
                    new YemekListesi { Tarih = bugun, Ogun = 2, Corba = "Mercimek Çorbası", AnaYemek = "İzmir Köfte", YardimciYemek = "Pirinç Pilavı", TatliMeyve = "Kemalpaşa Tatlısı", ToplamKalori = 850 }
                );
                context.SaveChanges();
            }

            // Bölümler
            if (!context.Bolumler.Any())
            {
                context.Bolumler.AddRange(
                    new Bolum { Ad = "Kardiyoloji", Aciklama = "Kalp sağlığı birimi", Kategori = "Dahili", IsActive = true },
                    new Bolum { Ad = "Genel Cerrahi", Aciklama = "Cerrahi müdahaleler", Kategori = "Cerrahi", IsActive = true }
                );
                context.SaveChanges();
            }

            // İlk Yetkili
            if (!context.Yetkililer.Any())
            {
                context.Yetkililer.Add(new Yetkili
                {
                    AdSoyad = "Hasret Özdemir",
                    Email = "admin@gazihastanesi.com",
                    SifreHash = "admin123",
                    Rol = "Süper Admin",
                    AdminSayfaYetkileri = AdminPanelPermissions.Serialize(AdminPanelPermissions.AllKeys),
                    IsActive = true,
                    KayitTarihi = DateTime.UtcNow
                });
                context.SaveChanges();
            }
        }

        private static void SeedAdminMenus(GaziHastaneContext context)
        {
            var menuItems = new AdminMenuItem[]
            {
                new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.Dashboard, Url = "/Admin/Home/Index", Label = "Gösterge Paneli", IconClass = "fa-solid fa-cube", Controller = "Home", HoverIconClass = "group-hover:text-cyan-400", SortOrder = 1 },
                new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.Doktorlar, Url = "/Admin/Doktorlar/Index", Label = "Doktorlar", IconClass = "fa-solid fa-user-doctor", Controller = "Doktorlar", HoverIconClass = "group-hover:text-purple-400", SortOrder = 2 },
                new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.Bolumler, Url = "/Admin/Bolumler/Index", Label = "Poliklinikler", IconClass = "fa-solid fa-network-wired", Controller = "Bolumler", HoverIconClass = "group-hover:text-pink-400", SortOrder = 3 },
                new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.HastaRehberi, Url = "/Admin/HastaRehberi/Index", Label = "Hasta Rehberi", IconClass = "fa-solid fa-book-medical", Controller = "HastaRehberi", HoverIconClass = "group-hover:text-emerald-400", SortOrder = 4 },
                new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.Iletisim, Url = "/Admin/Iletisim/Index", Label = "İletişim", IconClass = "fa-solid fa-address-book", Controller = "Iletisim", HoverIconClass = "group-hover:text-orange-400", SortOrder = 5 },
                new() { Section = "Main", PermissionKey = AdminPanelPermissions.Keys.BorcYonetimi, Url = "/Admin/BorcYonetim/Index", Label = "Borç Yönetimi", IconClass = "fa-solid fa-file-invoice-dollar", Controller = "BorcYonetim", HoverIconClass = "group-hover:text-yellow-400", SortOrder = 6 },

                new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.KaliteYonetimi, Url = "/Admin/HizliIslem/Kalite", Label = "Kalite Yönetimi", IconClass = "fa-solid fa-shield-heart", Controller = "HizliIslem", Action = "Kalite", HoverIconClass = "group-hover:text-blue-400", SortOrder = 1 },
                new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.Egitim, Url = "/Admin/Egitim/Index", Label = "Eğitim Komitesi", IconClass = "fa-solid fa-graduation-cap", Controller = "Egitim", HoverIconClass = "group-hover:text-orange-500", SortOrder = 2 },
                new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.YemekListesi, Url = "/Admin/HizliIslem/YemekListesi", Label = "Yemek Listesi", IconClass = "fa-solid fa-utensils", Controller = "HizliIslem", Action = "YemekListesi", HoverIconClass = "group-hover:text-orange-500", SortOrder = 3 },
                new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.Kroki, Url = "/Admin/Kroki/Index", Label = "Kroki Yönetimi", IconClass = "fa-solid fa-map-location-dot", Controller = "Kroki", HoverIconClass = "group-hover:text-cyan-400", SortOrder = 4 },
                new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.Medya, Url = "/Admin/HizliIslem/AnaSayfaGorsel", Label = "Ana Sayfa Slider", IconClass = "fa-solid fa-image", Controller = "HizliIslem", Action = "AnaSayfaGorsel", ActiveIconClass = "text-yellow-500 drop-shadow-[0_0_8px_rgba(234,179,8,0.8)] scale-110", HoverIconClass = "group-hover:text-yellow-400 group-hover:scale-110", SortOrder = 5 },
                new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.DoktorRandevuPlani, Url = "/Admin/DoktorRandevuPlan/Index", Label = "Doktor Planlama", IconClass = "fa-solid fa-calendar-plus", Controller = "DoktorRandevuPlan", HoverIconClass = "group-hover:text-cyan-400", SortOrder = 6 },
                new() { Section = "System", PermissionKey = AdminPanelPermissions.Keys.TahlilSonuclari, Url = "/Admin/TahlilSonuclari/Giris", Label = "Tahlil Sonuç Girişi", IconClass = "fa-solid fa-vials", Controller = "TahlilSonuclari", Action = "Giris", HoverIconClass = "group-hover:text-emerald-400", SortOrder = 7 },

                new() { Section = "Content", PermissionKey = AdminPanelPermissions.Keys.DijitalIslemler, Url = "/Admin/HizliIslem/Index", Label = "Dijital İşlemler", IconClass = "fa-solid fa-layer-group", Controller = "HizliIslem", Action = "Index", ActiveIconClass = "neon-icon text-cyan-400", HoverIconClass = "group-hover:text-cyan-400", SortOrder = 1 },
                new() { Section = "Content", PermissionKey = AdminPanelPermissions.Keys.Haberler, Url = "/Admin/Haberler/Index", Label = "Haberler", IconClass = "fa-solid fa-newspaper", Controller = "Haberler", HoverIconClass = "group-hover:text-blue-400", SortOrder = 2 },
                new() { Section = "Content", PermissionKey = AdminPanelPermissions.Keys.Etkinlikler, Url = "/Admin/Etkinlikler/Index", Label = "Etkinlikler", IconClass = "fa-solid fa-calendar-days", Controller = "Etkinlikler", HoverIconClass = "group-hover:text-fuchsia-400", SortOrder = 3 },
                new() { Section = "Content", PermissionKey = AdminPanelPermissions.Keys.Duyurular, Url = "/Admin/Duyurular/Index", Label = "Duyurular", IconClass = "fa-solid fa-bullhorn", Controller = "Duyurular", HoverIconClass = "group-hover:text-yellow-400", SortOrder = 4 },

                new() { Section = "Security", Url = "/Admin/Yetkililer/Index", Label = "Yetkili Kontrolü", IconClass = "fa-solid fa-user-shield", Controller = "Yetkililer", Action = "Index", HoverIconClass = "group-hover:text-rose-400", IsSuperAdminOnly = true, SortOrder = 1 }
            };

            foreach (var item in menuItems)
            {
                if (!context.AdminMenuItems.Any(x => x.Url == item.Url))
                {
                    context.AdminMenuItems.Add(item);
                }
            }
            context.SaveChanges();
        }
    }
}
